name: Build and Publish OpenDataPedia Docker image to Github Registry
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Build and Publish OpenDataPedia Docker image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the OpenDataPedia 'docker' repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd docker
          VERSION=$(cat ../VERSION.txt) && docker build --build-arg VERSION -t opendatapedia:${VERSION} .
      # - name: Log into Github Registry
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Push Docker image to GitHub Registry
      #   run: 